name: Auto-rebase Exercism Solutions
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-rebase:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'exercism-solutions-syncer[bot]'
    
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Add Label and Rebase
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          # 1. Add the label
          gh pr edit "$PR_URL" --add-label "exercism"
          
          # 2. Rebase and Merge the PR
          gh pr merge "$PR_URL" --rebase --delete-branch
